import { nanoid } from "nanoid"
export const bookData = [
    {
        id:nanoid(),
        img:'/assets/alexandra-fuller-4RNLzJzEMMs-unsplash.jpg',
        title:'A Brief History of Time ',
        author:'Stephen Hawking',
        type:'non_fiction',
        description:'This classic book explores the mysteries of the universe, including black holes, time travel, and the Big Bang, in a way that is accessible to general readers.',
        rating:'4.5',
    },
    {
        id:nanoid(),
        img:'/assets/scienceBook2.jpg',
        title:'The Selfish Gene',
        author:'Richard Dawkins',
        type:'fantasy',
        description:'Dawkins introduces the concept of the "selfish gene," explaining how genes drive evolution and behavior. The book is known for its clear explanation of complex biological ideas',
        rating:'4.5',
    },{
        id:nanoid(),
        img:'/assets/scienceBook3.jpg',
        title:'The Elegant Universe',
        author:'Brian Greene',
        type:'non_fiction',
        description:'This book delves into the world of string theory, a cutting-edge idea in physics that attempts to unify all fundamental forces of the universe. Greene makes complex concepts understandable and fascinating.',
        rating:'4.5',
    },{
        id:nanoid(),
        img:'/assets/debby-hudson-ERb-JXVwAfo-unsplash.jpg',
        title:'Sapiens',
        author:'Yuval Noah Harari',
        type:'Science',
        description:'Harari explores the history of humanity, from the evolution of Homo sapiens to the modern world, blending science, history',
        rating:'2.5',
    },{
        id:nanoid(),
        img:'/assets/scienceBook5.jpg',
        title:'The Gene',
        author:'Siddhartha Mukherjee',
        type:'non_fiction',
        description:'Harari explores the history of humanity, from the evolution of Homo sapiens to the modern world, blending science, history',
        rating:'4.2',
    },
    {
        id:nanoid(),
        img:'/assets/scienceBook1.jpg',
        title:'A Brief History of Time ',
        author:'Stephen Hawking',
        type:'fiction',
        description:'This classic book explores the mysteries of the universe, including black holes, time travel, and the Big Bang, in a way that is accessible to general readers.',
        rating:'4.2',
    },
    {
        id:nanoid(),
        img:'/assets/hans-jurgen-weinhardt-FZ5nx86tP2U-unsplash.jpg',
        title:'The Selfish Gene',
        author:'Richard Dawkins',
        type:'crime',
        description:'Dawkins introduces the concept of the "selfish gene," explaining how genes drive evolution and behavior. The book is known for its clear explanation of complex biological ideas',
        rating:'4.1',
    },{
        id:nanoid(),
        img:'/assets/karolina-grabowska-H_eb_VfG2Ow-unsplash.jpg',
        title:'The Elegant Universe',
        author:'Brian Greene',
        type:'crime',
        description:'This book delves into the world of string theory, a cutting-edge idea in physics that attempts to unify all fundamental forces of the universe. Greene makes complex concepts understandable and fascinating.',
        rating:'4.0',
    },{
        id:nanoid(),
        img:'/assets/lantai-kayu-indonesia-LaEBSXbAy9M-unsplash.jpg',
        title:'Sapiens',
        author:'Yuval Noah Harari',
        type:'fantacy',
        description:'Harari explores the history of humanity, from the evolution of Homo sapiens to the modern world, blending science, history',
        rating:'4.8',
    },{
        id:nanoid(),
        img:'/assets/lluvia-morales-Giiqkyg_7UE-unsplash.jpg',
        title:'The Gene',
        author:'Siddhartha Mukherjee',
        type:'fantacy',
        description:'Harari explores the history of humanity, from the evolution of Homo sapiens to the modern world, blending science, history',
        rating:'4.3',
    }
]